# Cloud Pak for Data Virtualization Masking Demonstration
This notebook will connect to a CP4D cluster and demonstrate how SQL can be run against a variety of data sources without requiring any knowledge of how these data sources are accessed.

The first step is to load the Db2 extensions that allow us to run Db2 commands directly against CP4D.

In [1]:
%run db2.ipynb

Db2 Extensions Loaded.

A connection to the database is required before we can run any SQL statements. Run the following statement to connect to the Cloud Pak for Data cluster. **Note:** If you need to change the connection information, edit the Connection document which is found in the table of contents.

This example uses connection2 which is a DATAENGINEER to show the data masking.

Connect with dataengineer0 or admin to show how data masking is invoked for non-admin users.

In [2]:
%sql connect to bigsql user dataengineer0 using tsdvlab host 10.0.0.201 port 31193

Connection successful.

In [3]:
%sql -a select * from DB2OLTPONCPD.CUSTOMER fetch first 10 rows only

,CUSTID,FIRSTNAME,LASTNAME,BIRTHDATE,STREET,CITY,STATE,ZIPCODE,EMAIL,PHONE,CARD_TYPE,CARD_NO
0,100000,Eugene,Brock,1960-10-13,Washington Avenue,Somerset,PA,15501,Eugene.Brock@snailmail.com,531-341-0361,DYNY,XXXXXXXXXX
1,100001,Susan,Chandler,1971-02-12,Elizabeth Street,Greenville,SC,29601,Su.Chandler@nada.com,859-223-3389,MCCD,XXXXXXXXXX
2,100002,Ethan,Merrill,1988-08-02,Buckingham Drive,Helena,MT,59601,Et.Merrill@nada.com,767-335-9433,VASA,XXXXXXXXXX
3,100003,Nancy,Wells,1959-03-11,Prospect Street,Twin Falls,ID,83301,Na.Wells@snailmail.com,388-588-8354,PKUP,XXXXXXXXXX
4,100004,James,Lambert,1951-02-12,Elm Street,Little Rock,AR,72201,Jam.Lambert@yetii.com,872-384-9838,PKUP,XXXXXXXXXX
5,100005,Christine,William,1957-05-06,Mulberry Street,Brighton,CO,80601,Ch.William@ijit.com,512-366-6999,VASA,XXXXXXXXXX
6,100006,Roy,Shelton,1977-01-04,Primrose Lane,New York,NY,10203,Ro.Shelton@yetii.com,547-308-5576,CASH,XXXXXXXXXX
7,100007,Julie,Randolph,1950-01-10,Franklin Avenue,Winchester,VA,22601,Jul.Randolph@snailmail.com,859-517-3776,CASH,XXXXXXXXXX
8,100008,Gregory,Sawyer,1998-06-04,Lakeview Drive,Quincy,IL,62301,Gr.Sawyer@yahii.com,412-218-1180,VASA,XXXXXXXXXX
9,100009,Patricia,Shepard,1963-04-06,Madison Street,Bear River City,UT,84301,Patricia.Shepard@giggle.com,678-289-3942,VASA,XXXXXXXXXX

In [4]:
%sql connect to bigsql user admin using CP4DDataFabric host 10.0.0.201 port 31193

Connection successful.

Scroll to the right to see the Credit Card column

In [5]:
%sql -a select * from DB2OLTPONCPD.CUSTOMER fetch first 10 rows only

,CUSTID,FIRSTNAME,LASTNAME,BIRTHDATE,STREET,CITY,STATE,ZIPCODE,EMAIL,PHONE,CARD_TYPE,CARD_NO
0,100000,Eugene,Brock,1960-10-13,Washington Avenue,Somerset,PA,15501,Eugene.Brock@snailmail.com,531-341-0361,DYNY,2185-7633-3330-4
1,100001,Susan,Chandler,1971-02-12,Elizabeth Street,Greenville,SC,29601,Su.Chandler@nada.com,859-223-3389,MCCD,5670-7099-6302-1
2,100002,Ethan,Merrill,1988-08-02,Buckingham Drive,Helena,MT,59601,Et.Merrill@nada.com,767-335-9433,VASA,8268-4203-5900-3
3,100003,Nancy,Wells,1959-03-11,Prospect Street,Twin Falls,ID,83301,Na.Wells@snailmail.com,388-588-8354,PKUP,9667-1981-6317-6
4,100004,James,Lambert,1951-02-12,Elm Street,Little Rock,AR,72201,Jam.Lambert@yetii.com,872-384-9838,PKUP,2596-3346-3361-7
5,100005,Christine,William,1957-05-06,Mulberry Street,Brighton,CO,80601,Ch.William@ijit.com,512-366-6999,VASA,9830-7216-9095-9
6,100006,Roy,Shelton,1977-01-04,Primrose Lane,New York,NY,10203,Ro.Shelton@yetii.com,547-308-5576,CASH,9245-6430-8432-9
7,100007,Julie,Randolph,1950-01-10,Franklin Avenue,Winchester,VA,22601,Jul.Randolph@snailmail.com,859-517-3776,CASH,2597-8773-7788-7
8,100008,Gregory,Sawyer,1998-06-04,Lakeview Drive,Quincy,IL,62301,Gr.Sawyer@yahii.com,412-218-1180,VASA,3203-9220-2838-5
9,100009,Patricia,Shepard,1963-04-06,Madison Street,Bear River City,UT,84301,Patricia.Shepard@giggle.com,678-289-3942,VASA,3782-3500-3003-9